version: "3.9"

services:
  go-app:
    container_name: go-app
    image: go-rest-api
    build: deployments/go-app/
    ports:
      - "8000:8000"
    depends_on:
      - go_db
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
  go_db:
    container_name: go-db
    image: postgres-go-api
    build: deployments/go-db/
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data